### ISSUE TITLE
.com => .org

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/okturtles.com#14]
We're a non-profit. We should TLD like it.
##

**Comment by taoeffect** [comment]
Done!

**Comment by john-light** [comment]
Yay! But.... umm..... I did not edit this issue 2 days ago :x 

![johnedit](https://user-images.githubusercontent.com/9424721/43157433-e3f1fafc-8f31-11e8-8d50-fbe0ebe761b6.png)

**Comment by taoeffect** [comment]
@john-light Did you set up your account with Bountysource for this repo? My guess is that's what it was.

**Comment by john-light** [comment]
@taoeffect not sure exactly, but I did see that Bountysource had access to GitHub. I have now revoked that access since I don't use it anymore.
