### ISSUE TITLE
Convert to Astro website

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/okturtles.com#56]
### Problem

When CSS is modified the changes sometimes do not appear on the live website because of caching issues.

### Solution

By using Astro instead of nginx SSI includes for the headers/footers, we can build the page using Astro's static site stuff and Astro will also handle creating a different CSS file each time it changes, guaranteeing that the changes immediately appear on the deployed site.

**Comment by SebinSong** [comment]
Feature branch for this issue: [**sebin/#56-convert-to-astro-website**](https://github.com/okTurtles/okturtles.com/commits/sebin/%2356-convert-to-astro-website)

cc. @taoeffect

**Comment by taoeffect** [comment]
> Btw, is /browser-extension just temporarily hidden and will be in use again in the future?

Please keep it. It is linked to from across the web, and it is something we might return to at some point.
